apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8s-55f4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8s-55f4"
  template:
    metadata:
      labels:
        app: "k8s-55f4"
    spec:
      containers:
        - name: "k8s-55f4"
          image: "k8sregistryluca.azurecr.io/k8s"
          ports:
          - containerPort: 8080